# Site
name: "Lady Loves"
title: "LadyLoves"
description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
formspree: 'https://formspree.io/f/xzzzqvbb'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sushil:
    name: Sushil Mohan
    display_name: Sushil M.

    email: codingrhodes@gmail.com
    linkedin: https://www.linkedin.com/in/sushil-m-37694b116
    description: "With over 4 years of experience as a Shopify developer, I am specialized in building robust, user-friendly online stores. Their expertise spans theme customization, app integration, and ecommerce optimization, making them a trusted resource for Shopify-related insights and strategies."


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# remove cach
BUNDLE_PATH: .bundle
BUNDLE_DISABLE_SHARED_GEMS: "1"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
